[workspace]
resolver = "2"
members = ["apps/caramba-node",
    "apps/caramba-panel", "libs/caramba-db", "libs/caramba-shared",
    "apps/caramba-sub", "apps/caramba-installer", "apps/caramba-bot",
]

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
strip = true
opt-level = "z"
